name: npm

on:
  push:
    branches-ignore:
      - master

jobs:
  stamps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run stamps
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: hyundai
          path: /home/runner/work/Kuvork/Kuvork/hyundai.european.token.collection.ts
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: kia
          path: /home/runner/work/Kuvork/Kuvork/kia.european.token.collection.ts
      - name: Display structure of downloaded files
          run: ls -R
      - name: Download hyundai file
        uses: actions/download-artifact@v2
        with:
          name: hyundai
          path: bla.txt

      # two articacts are saved. Put them in the repo 
  #test:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #    - run: npm ci
  #    - run: npm test
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #    - run: npm ci
  #    - run: npm run build
