name: npm

on:
  push:
    branches-ignore:
      - master

jobs:
  stamps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - echo "the project directory is - $CI_PROJECT_DIR"
      - cat $CI_PROJECT_DIR/README.md ; echo
      - echo "and where am I? - $PWD"
      - run: npm run stamps
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
